### ISSUE TITLE
Can non-eloquent resources branch be merged into master?

### ISSUE THREAD

**Issue by maartenpaauw** [swisnl/openapi-spec-generator#23]
Title says all.

**Comment by JaZo** [comment]
You mean https://github.com/swisnl/openapi-spec-generator/pull/22? 😄

**Comment by maartenpaauw** [comment]
Besides the sync PR, what are the blockers for merging `non-eloquent-resources` into `master` and drafting a new release? I can offer some help.

**Comment by JaZo** [comment]
I'm not sure, I'll leave that question to @Rocksheep, as it's his work.

**Comment by Rocksheep** [comment]
Hi @maartenpaauw. Sadly I haven't had time to finish the feature for non-eloquent-resources. I'll have to look into where I was headed with my code as I touched it last a year ago.

**Comment by Rocksheep** [comment]
@maartenpaauw it took a bit longer, but we just released version [0.7.0](https://github.com/swisnl/openapi-spec-generator/releases/tag/0.7.0)! It's now possible to generate documentation for non eloquent resources.
